pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh '''
                        rm -rf venv
                        python3 -m venv venv
                        venv/bin/python -m pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Deploy Flask') {
            steps {
                dir('backend') {
                    sh '''
                        pm2 delete flask-backend || true
                        pm2 start app.py --name flask-backend --interpreter ./venv/bin/python
                        pm2 save
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Flask backend deployed successfully!'
        }

        failure {
            echo 'Flask backend deployment failed!'
        }
    }
}
