pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh '''
                        python3 -m venv venv
                        ./venv/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Deploy Flask') {
            steps {
                dir('backend') {
                    sh '''
                        pm2 restart flask-backend
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Flask backend deployed successfully!'
        }
        failure {
            echo 'Flask backend deployment failed!'
        }
    }
}
